### ISSUE TITLE
Openers not saving?

### ISSUE THREAD

**Issue by Zeffuro** [herulume/OpenerCreator#11]
I trid to make the Dancer opener: 
![ffxiv_dx11_2024-07-16_03-49-30](https://github.com/user-attachments/assets/d8ed10c1-0cb0-4d73-ae35-a2e3d0f66c87)

But it would not save, I have tried saving other openers but none of them seem to save no matter what action I put it.
Nothing my in log.

Also it would be nice if we could have the oGCDs be shifted upward or to have something that allows any oGCDs (since with DNC it's possible to have both Fan Dance and Fan Dance 3 procs and order of use might differ from pull to pull depending on the procs

**Comment by herulume** [comment]
Hey! Thank you for reporting this.

I will look into the not-saving bugs.

Regarding procs on DNC, I admit I have thought about it and I'm considering creating the notion of "possible GCDs" so we can add more descriptive openers (without needing to add the catch-all action). This would also allow us to add BRD's opener.

I also completely agree regarding oGCDs being a bit upwards since it would improve user experience. I will also take a look into it but it will be a bit lower priority.

**Comment by herulume** [comment]
There is a bug where if you save an opener with the job set to ANY, it won't be shown in the loader tab since we don't display them.
I've updated the plugin not to allow saving openers if the job is ANY (not released yet). It will also show an error message indicating what to change.

**Comment by herulume** [comment]
The bug has been fixed, and the suggestions will be implemented in future releases.

**Comment by Zeffuro** [comment]
Thank you, sorry I forgot to respond earlier 4 days but yeah I can confirm the bug is fixed!
